Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'spec/spec_helper.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'vcr_cassettes/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashEachMethods:
  Enabled: true
