version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  coverage-reporter: codacy/coverage-reporter@7.8.1

jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: |
            gem install bundler:2.1.2
            bundle check --path=vendor/bundle || bundle install  --jobs=4 --retry=3

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: coverage

      - coverage-reporter/send_report

  rubocop:
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: gem install bundler:2.1.2 && bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: Lint with rubocop
          command: bundle exec rubocop

workflows:
  version: 2

  build:
    jobs:
      - rubocop
      - rspec
